CC=gcc
CFLAGS=-Wall -Wconversion -g 

esercizio_01: esercizio_01.c

esercizio_02: esercizio_02.c

esercizio_03: esercizio_03.c

esercizio_04: esercizio_04.c

esercizio_05: esercizio_05.c

esercizio_06: esercizio_06.c

esercizio_07: esercizio_07.c


clean:
	rm -f esercizio_01 esercizio_02 esercizio_03 esercizio_04 esercizio_05 esercizio_06 esercizio_07